services : 
######################################################
# AIRFLOW
######################################################

  airflow:
    build: ./Docker/airflow
    restart: always
    container_name: airflow
    volumes:
      - ./mnt/airflow/dags:/opt/airflow/dags
      - ./mnt/airflow/spark:/opt/airflow/spark
      - ./mnt/airflow/plugins:/opt/airflow/plugins
      - ./mnt/airflow/kafka:/opt/airflow/kafka
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "nc", "-z", "airflow", "8080" ]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - bigdata-network
######################################################
# DATABASE SERVICE
######################################################
  postgres:
    image: postgres:13
    restart: always
    container_name: postgres
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    ports:
      - 5432:5432
    #volumes:
      #- ./mnt/postgres:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow_db
      #- PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "airflow_db", "-U", "airflow" ]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - bigdata-network

######################################################
# NETWORK
######################################################
networks:
  bigdata-network:
    driver: bridge
