services : 
######################################################
# DATABASE SERVICE
######################################################
  postgres:
    image: postgres:13
    restart: always
    container_name: postgres
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow_db
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "airflow_db", "-U", "airflow"]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - bigdata-network
######################################################
# AIRFLOW
######################################################

  airflow:
    build: ./docker/airflow
    restart: always
    container_name: airflow
    volumes:
      - ./mnt/airflow/dags:/opt/airflow/dags
      - ./mnt/airflow/logs:/opt/airflow/spark
      - ./mnt/airflow/plugins:/opt/airflow/plugins
      - ./FPL:/opt/airflow/fpl_functions
      - ./dbt_fpl:/opt/airflow/dbt
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "nc", "-z", "airflow", "8080" ]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - bigdata-network

  docker-proxy:
    image: alpine/socat
    command: "TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock"
    ports:
      - "2376:2375"
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./dbt_fpl:/datadrive/dbt/dbt_fpl
      - ~/.dbt:/home/dbtuser/.dbt
    networks:
      - bigdata-network
######################################################
# NETWORK
######################################################
networks:
  bigdata-network:
    driver : bridge
