version: "3.7"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: fpluser
      POSTGRES_PASSWORD: fplpassword
      POSTGRES_DB: fpl_db
    ports:
      - "5432:5432"
    volumes:
      - fpl-postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword
    ports:
      - "9000:9000"  # MinIO web UI
      - "9001:9001"  # MinIO API
    volumes:
      - fpl-minio-data:/data


  airflow:
    image: apache/airflow:2.4.0
    depends_on:
      - postgres
      - minio
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://fpluser:fplpassword@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt_project:/opt/airflow/dbt_project
    command: > 
      bash -c "
        airflow db init &&
        airflow users create \
          --username admin \
          --firstname Airflow \
          --lastname Admin \
          --role Admin \
          --email admin@example.com \
          --password admin &&
        airflow webserver --port 8080 -D &
        airflow scheduler -D 
      "
volumes:
  fpl-postgres-data:
  fpl-minio-data: