dbt_fpl: # Choose a descriptive name for your profile
  target: dev # You can use 'dev', 'prod', etc. for different environments
  outputs:
    dev:
      type: postgres # Or the type of your database (e.g., snowflake, redshift)
      host: postgres # Your PostgreSQL host
      port: 5432  # Your PostgreSQL port 
      user: airflow # Your PostgreSQL username
      password: airflow # Your PostgreSQL password
      dbname: airflow_db  # Your PostgreSQL database name
      schema: public # Or the schema you want to use 
  threads: 4 # Number of threads to use for parallel execution 